name: Dependency Check (OWASP)
on:
  schedule:
    - cron: '48 02 * * 0' # Each Sunday at 02:48 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Execute Dependency Check
        run: mvn --batch-mode dependency-check:check