name: ci-main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created
      - edited
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'dgc-github'
          server-username: GITHUB_USER
          server-password: GITHUB_PAT
      - name: Build
        run: mvn --batch-mode install
        env:
          GITHUB_USER: ${{ secrets.GPR_USER }}
          GITHUB_PAT: ${{ secrets.GPR_PAT }}
      - name: Build ZIP
        uses: papeloto/action-zip@v1
        with:
          files: target/dgc-cli.jar src/wrapper/dgc.bat
          recursive: true
          dest: dgc-cli.zip
      - name: Publish to Release
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-name: Latest
          tag-name: HEAD
          asset-name: dgc-cli.zip
          file: dgc-cli.zip
