name: ci-main
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'dgc-github'
          server-username: GITHUB_USER
          server-password: GITHUB_PAT
      - name: Build
        run: mvn --batch-mode package
        env:
          GITHUB_USER: ${{ secrets.GPR_USER }}
          GITHUB_PAT: ${{ secrets.GPR_PAT }}
      - name: Build ZIP
        uses: papeloto/action-zip@v1
        with:
          files: target/dgc-cli.jar src/wrapper/dgc.bat
          recursive: true
          dest: dgc-cli.zip
      - name: Create new latest release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifact: dgc-cli.zip
          body: Automatic Build of latest code in main branch.
          draft: true
          name: Development Build (autmatic)
          commit: main
          tag: automatic-build
          token: ${{ secrets.GITHUB_TOKEN }}
